### ISSUE TITLE
Cable_box

### ISSUE THREAD

**Issue by jeb2239** [Jfach/Optimum-TV-API#1]
What is the cable_box import?

**Comment by jfach** [comment]
@jeb2239 Believe it or not, it looks like I forgot to commit that module two years ago when I created this repository! It's a fairly simple module, containing only one class, `Box`.  The `Box` class is just a simple object just to hold the values of various properties of a physical cable box, which are set by `__init__`. Looking through the code I can see these properties are:
- `name`, the name of the cable box
- `serial`, the serial number of the cable box
- `recordable`, a boolean value that denotes whether or not content can be recorded to the cable box
- `resolution`, the output resolution of the cable box
- `type`, the type of cable box
- `space`, the storage capacity of the cable box

**Comment by jfach** [comment]
Thanks for bringing my attention to this, #2 closes this. Feel free to reopen this issue or create another one if you run into any problems.
